### ISSUE TITLE
No screens found

### ISSUE THREAD

**Issue by Nikolay0054** [freedreno/xf86-video-freedreno#2]
Adreno 305, Debian chroot on android. With fbdev works, but i got segmentation fault
Log:
[Xorg.0.txt](https://github.com/freedreno/xf86-video-freedreno/files/219353/Xorg.0.txt)

**Comment by robclark** [comment]
I guess missing the kgsl drm shim driver enabled in kernel?

**Comment by Nikolay0054** [comment]
I dont know, but i have kernel [source code](http://dlcdnet.asus.com/pub/ASUS/ZenFone/A500KL/ASUS_A500KL_11_4_6_106_kernel.zip)

**Comment by Nikolay0054** [comment]
I need compile it with this driver?

**Comment by robclark** [comment]
yes..  also just double check that the device file exists and it isn't just a permissions problem or something like that.. but one way or another it is unable to open /dev/dri/card0

**Comment by Nikolay0054** [comment]
Yep. No such file or directory

**Comment by Nikolay0054** [comment]
Can you help me with compile kernel?

**Comment by Nikolay0054** [comment]
Oh. I downloaded latest version of eabi and it compile fine!

**Comment by Nikolay0054** [comment]
I'm got no such file or directory errors :(

**Comment by Nikolay0054** [comment]
Yeah. It compile fine now!

**Comment by Nikolay0054** [comment]
Can you give me tutorial?

**Comment by Nikolay0054** [comment]
I changed pc and toolchain and i think it compile with no errors

**Comment by Nikolay0054** [comment]
at the end error
[log.txt](https://github.com/freedreno/xf86-video-freedreno/files/221332/log.txt)

**Comment by robclark** [comment]
not really sure.. maybe phone vendor provided an incorrect kernel src code drop?  :-(

**Comment by Nikolay0054** [comment]
can you give me a link to the toolchain, which you use?

**Comment by Nikolay0054** [comment]
nevermind. i downloaded other version with no error

**Comment by Nikolay0054** [comment]
new errors
[log1.txt](https://github.com/freedreno/xf86-video-freedreno/files/223349/log1.txt)

**Comment by robclark** [comment]
as far as toolchain, I had mostly just used fedora's already-packaged arm cross compiler toolchain.  (Mostly just because I didn't have android NDK installed.)  Although it's been a long time since I've built 3.4 or older kernel (I only have one computer left with an old enough gcc to build even 3.10, let alone older).

**Comment by Nikolay0054** [comment]
You dont know how solve errors?
[log](https://github.com/freedreno/xf86-video-freedreno/files/223349/log1.txt)

**Comment by robclark** [comment]
offhand, no.. I think the kgsl_drm code is unfortunately not built/tested much by qcom so possibly they changed some things and didn't fix up the kgsl_drm code

**Comment by Nikolay0054** [comment]
Can you tell me smartphone with drm support?

**Comment by robclark** [comment]
I believe qcom uses kgsl_drm for their tizen work.. not sure if that is in any shipping phone.  I did manage to get it working once upon a time (several years back) on msm-3.4 based kernel in the nexus4.

**Comment by Nikolay0054** [comment]
I can use freedreno driver without drm?

**Comment by robclark** [comment]
you need drm, at least for dri2/x11..  maybe with a new backend in libdrm_freedreno it could be made to work in stand-alone (single process, no compositor/x11) mode using only kgsl.  Not sure if that is *easier*.. vs fixing whatever is needed to make kgsl_drm work.. and it is certainly more limiting.

**Comment by Nikolay0054** [comment]
Ok now i don't have problem with drm, but i have new problems with usb :(
[log.txt](https://github.com/freedreno/xf86-video-freedreno/files/254119/log.txt)

**Comment by Nikolay0054** [comment]
Maybe i have bad compiler?

**Comment by Nikolay0054** [comment]
Nevermind. I'm disabled coresight and FINALLY it compiles!

**Comment by Nikolay0054** [comment]
How to pack zImage in boot.img?

**Comment by robclark** [comment]
which kernel version?  Older (3.4/pre-devicetree) kernels (and maybe 3.10 kernels if you don't have a dt aware bootloader): `abootimg --create ifc6410-boot.img -k ../msm/arm/arch/arm/boot/zImage -f ./bootimg.cfg -r initramfs-3.4.0-g0f0fed7-00108-gf736ca1-dirty.img `

(and you can use `abootimg -x`, iirc, to extract an existing ramdisk/bootimg.cfg..)

With dt aware bootloader, you need to use a different tool..  I'll have to dig up git tree / instructions..

**Comment by Nikolay0054** [comment]
I'm got error about missing dtb. Trying compile it from dts.

**Comment by Nikolay0054** [comment]
Found 0 unique DTB(s) :( How to compile dts files?

**Comment by robclark** [comment]
try the `dtbs` make target, ie. `make ARCH=.... ... dtbs`?

**Comment by Nikolay0054** [comment]
The purpose of `arch/arm/boot/dtbs' does not require the execution of commands.(Google Translate)

**Comment by Nikolay0054** [comment]
ummmmm

**Comment by Nikolay0054** [comment]
I'm always trying fastboot boot new_boot.img. Now i trying fastboot flash boot boot.img and success

**Comment by Nikolay0054** [comment]
Load kernel failed -_-

**Comment by Nikolay0054** [comment]
`make A500KL_ER1_msm8926-v1-720p-mtp.dtb` makes me a dtb file but dtbTool still not seeing it

**Comment by Nikolay0054** [comment]
:O I downloaded mkqcdtbootimg from sony and in options set dt dir. No error but it rebooted and loaded recovery

**Comment by Nikolay0054** [comment]
ITS ALIVE! MY FIRST CUSTOM KERNEL

**Comment by Nikolay0054** [comment]
wifi not working, mobile network not working bluetooth working

**Comment by Nikolay0054** [comment]
Trying compile kernel with wifi and mobile network

**Comment by Nikolay0054** [comment]
maybe i have wrong source code

**Comment by Nikolay0054** [comment]
Can you help me compile freedreno on arch?

**Comment by Nikolay0054** [comment]
i'm compiled xf86 freedreno and installed it but xorg says module doesnt exist

**Comment by robclark** [comment]
re: wifi (and possibly bluetooth?), on at least some of the devices (like, iirc, my nexus4) they used compat-wireless tree to build a newer wifi driver with older kernel.

re: xorg/freedreno, be sure to build libdrm with --enable-freedreno-kgsl.  Double check the device files exist (it should look for /dev/fb0, /dev/dri/card0, and /dev/kgsl-3d0).. path to fb device might be different on android but there is a config file option, like:

  Option "fb" "/dev/graphics/fb0"

double check the freedreno man page..

**Comment by Nikolay0054** [comment]
I found a lot of dts files for my phone. Maybe i need to add all of them?
